version: '3'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  rabbitmq:
    image: 'rabbitmq:3'
    ports:
      - '5672:5672'
      - '15672:15672'
  celery:
    container_name: parser
    build:
      dockerfile: Dockerfile
    restart: always
    environment:
      - BROKER_URL=${BROKER_URL}
      - RESULT_BACKEND=${RESULT_BACKEND}
    depends_on:
      - rabbitmq
      - redis
      - db_mysql
      - phpmyadmin
    links:
      - rabbitmq
      - redis
      - db_mysql
      - phpmyadmin
    volumes:
      - /mnt/parser:/myapp
  db_mysql:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db_mysql
    links:
      - db_mysql
  fastapi:
    build:
      dockerfile: Dockerfile
    command: [ "uvicorn", "FastAPI.parser_api:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
    ports:
      - "8000:8000"
    volumes:
      - /mnt/parser:/myapp
    depends_on:
      - rabbitmq
      - redis
      - db_mysql
      - phpmyadmin
      - celery