FROM python:3.10
WORKDIR /myapp
COPY requirements.txt /myapp
COPY src /myapp
RUN pip install -r requirements.txt
COPY .env /myapp/
CMD  [ "uvicorn", "src.services.parser.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]