version: '3'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  rabbitmq:
    image: 'rabbitmq:3'
    ports:
      - '5672:5672'
      - '15672:15672'
  celery:
    build: . # подключение dockerfile
    restart: always
    environment:
      - BROKER_URL=amqp://rabbitmq:5672//
      - RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - rabbitmq
      - redis
      - db_mysql
      - phpmyadmin
    links:
      - rabbitmq
      - redis
      - db_mysql
      - phpmyadmin
    volumes:
      - /media/dima/Новый том/Trainee/parser:/myapp
    container_name: parser
  db_mysql:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: library
      MYSQL_USER: dima
      MYSQL_PASSWORD: 12345
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db_mysql
    links:
      - db_mysql