version: '3'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  rabbitmq:
    image: 'rabbitmq:3'
    ports:
      - '5672:5672'
      - '15672:15672'
  db_mysql:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./.env
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PORT=${MYSQL_PORT}
    ports:
      - '3306:3306'
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db_mysql
    links:
      - db_mysql
  celery:
    build:
      dockerfile: Dockerfile
      target: celery-stage
    restart: always
    env_file:
      - ./.env
    environment:
      - BROKER_URL=${BROKER_URL}
      - RESULT_BACKEND=${RESULT_BACKEND}
    depends_on:
      - rabbitmq
      - redis
      - db_mysql
      - phpmyadmin
    links:
      - rabbitmq
      - redis
      - db_mysql
      - phpmyadmin
    volumes:
      - ~/parser/src:/myapp/src
      - ~/parser/celery_worker:/myapp/celery_worker
      - ~/parser/parser:/myapp/parser
  api_services:
    build:
      dockerfile: Dockerfile
      target: fastapi-stage
    env_file:
      - ./.env
    environment:
      - SIGNATURE=${SIGNATURE}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    ports:
      - "8000:8000"
    volumes:
      - ~/parser/src:/myapp/src
      - ~/parser/celery_worker:/myapp/celery_worker
      - ~/parser/parser:/myapp/parser
    depends_on:
      - rabbitmq
      - redis
      - db_mysql
      - phpmyadmin
      - celery