version: '3'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  rabbitmq:
    image: 'rabbitmq:3'
    ports:
      - '5672:5672'
      - '15672:15672'
  db_mysql:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_HOST=db_mysql
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=library
      - MYSQL_USER=dima
      - MYSQL_PASSWORD=12345
      - MYSQL_PORT=3306
    ports:
      - '3306:3306'
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db_mysql
    links:
      - db_mysql
  celery:
    build:
      dockerfile: Dockerfile
      target: celery-stage
    restart: always
    environment:
      - BROKER_URL=${BROKER_URL}
      - RESULT_BACKEND=${RESULT_BACKEND}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PORT=${MYSQL_PORT}
    depends_on:
      - rabbitmq
      - redis
      - db_mysql
      - phpmyadmin
    links:
      - rabbitmq
      - redis
      - db_mysql
      - phpmyadmin
    volumes:
      - /mnt/parser/src:/myapp/src
  api_services:
    build:
      dockerfile: Dockerfile
      target: fastapi-stage
    ports:
      - "8000:8000"
    volumes:
      - /mnt/parser/src:/myapp/src
    depends_on:
      - rabbitmq
      - redis
      - db_mysql
      - phpmyadmin
      - celery