apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  MYSQL_USER: "ZGltYQ=="
  MYSQL_PASSWORD: "MTIzNDU="
  MYSQL_ROOT_PASSWORD: "MTIzNDU="

  SIGNATURE: "ZTA3ZmZhN2U3NzFkNzJhOTA4MmMwZmM2ZjNhNzc1MTdjNWE2ZmEzOGRhOWNkZDlmZGZlNzA4YjFjMjQ4NDk3NA=="

  GOOGLE_CLIENT_ID: "NzY3MzczNDQ3NDY3LTVoNzZjOW9vNGc2a2dmcmJ0YmdhaWU5dXFnNHFyNWU0LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t"
  GOOGLE_CLIENT_SECRET: "R09DU1BYLW4tUUt0T0Q3MUFQZE5NNDh6RTB0TXNsRVlUeDM="

  APPLICATION_PASSWORD: "dXBsem9zZ3lkcHJ1dGp1Zg=="


