"""empty message

Revision ID: ddd4222177e1
Revises:
Create Date: 2024-04-30 17:48:39.540224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ddd4222177e1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('date', sa.Date(), nullable=True),
                    sa.Column('book_num', sa.BigInteger(), nullable=True),
                    sa.Column('title', sa.String(length=255), nullable=True),
                    sa.Column('author', sa.String(length=255), nullable=True),
                    sa.Column('price_new', sa.DECIMAL(precision=10, scale=2), nullable=True),
                    sa.Column('price_old', sa.DECIMAL(precision=10, scale=2), nullable=True),
                    sa.Column('discount', sa.String(length=20), nullable=True),
                    sa.Column('rating', sa.DECIMAL(precision=4, scale=2), nullable=True),
                    sa.Column('image', sa.String(length=255), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('book_num')
                    )
    op.create_table('books_history',
                    sa.Column('book_id', sa.Integer(), nullable=False),
                    sa.Column('date', sa.Date(), nullable=True),
                    sa.Column('book_num', sa.BigInteger(), nullable=True),
                    sa.Column('title', sa.String(length=255), nullable=True),
                    sa.Column('price_new', sa.DECIMAL(precision=10, scale=2), nullable=True),
                    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
                    sa.PrimaryKeyConstraint('book_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books_history')
    op.drop_table('books')
    # ### end Alembic commands ###
