apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: celery-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: celery-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60