apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: db-mysql-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: db-mysql-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60