"""empty message

Revision ID: 002c0484eea0
Revises: 0be2ae562901
Create Date: 2024-05-17 13:19:57.127322

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "002c0484eea0"
down_revision: Union[str, None] = "0be2ae562901"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "history",
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("book_num", sa.BigInteger(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("price", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("books_history")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "books_history",
        sa.Column("book_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("book_num", mysql.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("title", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("price", mysql.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(["book_id"], ["books.id"], name="books_history_ibfk_1"),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.drop_table("history")
    # ### end Alembic commands ###
