"""empty message

Revision ID: 30e95078f630
Revises: c1893e5299d0
Create Date: 2024-05-05 16:22:24.304785

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "30e95078f630"
down_revision: Union[str, None] = "c1893e5299d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "books",
        "price_new",
        existing_type=mysql.DECIMAL(precision=10, scale=2),
        nullable=True,
    )
    op.alter_column(
        "books_history",
        "book_num",
        existing_type=mysql.BIGINT(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "books_history",
        "book_num",
        existing_type=mysql.BIGINT(),
        nullable=False,
    )
    op.alter_column(
        "books",
        "price_new",
        existing_type=mysql.DECIMAL(precision=10, scale=2),
        nullable=False,
    )
    # ### end Alembic commands ###
