"""empty message

Revision ID: c1893e5299d0
Revises: 9e889ca36fa6
Create Date: 2024-05-05 16:00:48.127811

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "c1893e5299d0"
down_revision: Union[str, None] = "9e889ca36fa6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "books",
        "book_num",
        existing_type=mysql.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.alter_column(
        "books_history",
        "book_num",
        existing_type=mysql.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "books_history",
        "book_num",
        existing_type=sa.BigInteger(),
        type_=mysql.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "books",
        "book_num",
        existing_type=sa.BigInteger(),
        type_=mysql.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
