apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-deployment
  labels:
    app: celery-deployment
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
        - name: celery-container
          image: localhost:5000/celery_image:v1
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          command: [ "celery", "-A", "celery_worker.config.celery_configs", "worker", "-l", "info", "-B" ]